### ISSUE TITLE
Documentation build fails

### ISSUE THREAD

**Issue by terrorfisch** [qutech/qupulse#410]
`Deque` is introduced in python 3.6.1 (https://docs.python.org/3/library/typing.html#typing.Deque)
Why don't the tests fail?

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/qupulse/envs/latest/lib/python3.5/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/qupulse/envs/latest/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 25, in <module>
    import qupulse
  File "/home/docs/checkouts/readthedocs.org/user_builds/qupulse/checkouts/latest/qupulse/__init__.py", line 2, in <module>
    from . import pulses
  File "/home/docs/checkouts/readthedocs.org/user_builds/qupulse/checkouts/latest/qupulse/pulses/__init__.py", line 4, in <module>
    from qupulse.pulses.function_pulse_template import FunctionPulseTemplate as FunctionPT
  File "/home/docs/checkouts/readthedocs.org/user_builds/qupulse/checkouts/latest/qupulse/pulses/function_pulse_template.py", line 21, in <module>
    from qupulse.pulses.pulse_template import AtomicPulseTemplate, MeasurementDeclaration
  File "/home/docs/checkouts/readthedocs.org/user_builds/qupulse/checkouts/latest/qupulse/pulses/pulse_template.py", line 18, in <module>
    from qupulse._program._loop import Loop, to_waveform
  File "/home/docs/checkouts/readthedocs.org/user_builds/qupulse/checkouts/latest/qupulse/_program/_loop.py", line 2, in <module>
    from typing import Union, Dict, Set, Iterable, FrozenSet, Tuple, cast, List, Optional, DefaultDict, Deque, Generator
ImportError: cannot import name 'Deque'
```

**Comment by terrorfisch** [comment]
Works again.
