### ISSUE TITLE
Bug in TimeType.from_float

### ISSUE THREAD

**Issue by peendebak** [qutech/qupulse#539]
A minimal example is:
```
TimeType.from_float(9926.666666667, absolute_error=1e-9)
```
which generates the error:
```
Traceback (most recent call last):

  File "<ipython-input-5-e956dddfd05d>", line 1, in <module>
    TimeType.from_float(9926.666666667, absolute_error=1e-9)

  File "c:\projects\qupulse\qupulse\utils\types.py", line 222, in from_float
    return cls(qupulse_numeric.approximate_double(value, absolute_error, fraction_type=cls._InternalType))

  File "c:\projects\qupulse\qupulse\utils\numeric.py", line 106, in approximate_double
    return approximate_rational(fraction_type(x), fraction_type(abs_err), fraction_type=fraction_type)

TypeError: cannot create 'mpq' instances
```

The problem is that `TimeType._InternalType` which is a type, is used as a constructor via `qupulse_numeric.approximate_double(value, absolute_error, fraction_type=cls._InternalType)`

@terrorfisch

**Comment by qutech-lab** [comment]
This seems to be an error introduced in gmpy2 2.0.8. Does not occur in gmpy 2.1.0b1

**Comment by terrorfisch** [comment]
@peendebak #541 should fix this bug

**Comment by terrorfisch** [comment]
Please reopen if there are still errors
