### ISSUE TITLE
Tests fail with new sympy version

### ISSUE THREAD

**Issue by terrorfisch** [qutech/qupulse#554]
```
Traceback (most recent call last):

  File "/home/travis/build/qutech/qupulse/tests/pulses/loop_pulse_template_tests.py", line 473, in test_get_serialization_data_all_features_old

    measurements=measurements, parameter_constraints=parameter_constraints)

  File "/home/travis/build/qutech/qupulse/qupulse/pulses/loop_pulse_template.py", line 123, in __init__

    ParameterConstrainer.__init__(self, parameter_constraints=parameter_constraints)

  File "/home/travis/build/qutech/qupulse/qupulse/pulses/parameters.py", line 249, in __init__

    for constraint in parameter_constraints]

  File "/home/travis/build/qutech/qupulse/qupulse/pulses/parameters.py", line 249, in <listcomp>

    for constraint in parameter_constraints]

  File "/home/travis/build/qutech/qupulse/qupulse/pulses/parameters.py", line 190, in __init__

    if not isinstance(self._expression, sympy.boolalg.Boolean):

AttributeError: module 'sympy' has no attribute 'boolalg'
```

**Comment by terrorfisch** [comment]
Fixed in #555
